

exercice1-partie1:
	flex binaire.lex
	gcc lex.yy.c -o binaire
	./binaire $(ARGS)
exercice1-partie2:
	flex partie2.lex
	gcc lex.yy.c -o partie2
	./partie2
exercice1-id-nb:
	flex id-nb.lex
	gcc lex.yy.c -o id-nb
	./id-nb